#+title: Jotix dotfiles

* dotfiles
** gitconfig
#+begin_src conf :tangle ~/.config/git/config :mkdirp yes
  [user]
  email = jujodeve@gmail.com
  name = jotix  
#+end_src
** gpg-agent.conf
#+begin_src conf :tangle ~/.gnupg/gpg-agent.conf :mkdirp yes
  allow-emacs-pinentry
#+end_src
** qutebrowser
#+begin_src python :tangle ~/.config/qutebrowser/config.py :mkdirp yes
  config.load_autoconfig(False)

  # tab are windows
  c.tabs.tabs_are_windows = True

  # hide statusbar
  #c.statusbar.show = "never"

  # hide tab bar
  c.tabs.show = "never"

  # window title format
  c.window.title_format = "qute{title_sep}{perc}{current_title}"
#+end_src
* docs
*** pulseaudio split front/rear
Splitting front/rear

Connect speakers to front analog output and headphones to rear output. It would be useful to split front/rear to separate sinks. Add to /etc/pulse/default.pa:

load-module module-remap-sink sink_name=speakers sink_properties="device.description='Speakers'" remix=no master=alsa_output.pci-0000_0a_00.3.analog-surround-40 channels=2 master_channel_map=front-left,front-right channel_map=front-left,front-right
load-module module-remap-sink sink_name=headphones sink_properties="device.description='Headphones'" remix=no master=alsa_output.pci-0000_0a_00.3.analog-surround-40 channels=2 master_channel_map=rear-left,rear-right channel_map=front-left,front-right

Make sure to replace alsa_output.pci-0000_05_00.0.analog-surround-40 with the sound card name shown in 'pacmd list-sinks'. Now you have 2 additional sinks which can be used separately. You can choose 'sink_name' freely, as long as there is no sink with that name already. The 'remix' parameter controls whether the audio should be down-/upmixed to match the channels in the sink.
Tip: If pulseaudio fails with master sink not found, comment out the remapping lines, start PulseAudio and verify your card output is set to the one you specified (e.g. analog surround 4.0). Alternatively, try using a sink index[broken link: invalid section] instead of a sink name.

*** pulseaudio separate headphones speakers
Having both speakers and headphones plugged in and switching in software on-the-fly

By design, Pulseaudio automatically turns off Line Out when headphones are plugged in and uses Headphone slider instead. You can observe this behavior in alsamixer. What we want is to have Headphone and Line Out sliders working separately and at the same time. This is extremely useful if you want to remap Realtek's jacks to have, say, Rear Green for headphones and Blue for speakers (with the help of hdajackretask from alsa-tools).

To achieve this, you should directly edit Pulseaudio mixer's configuration.

1. We tell pulseaudio that headphones are always plugged in. Edit:

/usr/share/pulseaudio/alsa-mixer/paths/analog-output-lineout.conf

Find:

[Jack Headphone]
state.plugged = no
state.unplugged = unknown

Change no to yes

2. By default, Line Out's volume controlled only by Master, and not by Line Out slider itself. We want to merge Line Out with Master.

Add this snippet to the end of the file:

[Element Line Out]
switch = mute
volume = merge

3. We need to completely cut off Line Out when we use headphones. Edit:

/usr/share/pulseaudio/alsa-mixer/paths/analog-output-headphones.conf

Add this snippet to the end of the file:

[Element Line Out]
switch = off
volume = off

4. Like Pulseaudio, Alsa itself cuts off speakers when headphones are plugged in. Open alsamixer (in case of Realtek HDA alsamixer -c0) and change Auto-Mute mode to disabled.

5. Restart Pulseaudio

$ pulseaudio -k
$ pulseaudio --start

Now you have two separate ports on the same sink in pulseaudio. They mute each other, so you can switch to headphones and this will mute Line Out, and vice versa. To switch between ports you can use Gnome or Plasma sound mixer, or install appropriate desktop extension. 
*** kernel parameters
To make the change persistent after reboot, you could manually edit /boot/grub/grub.cfg with the exact line from above, but the best practice is to:
Edit /etc/default/grub and append your kernel options between the quotes in the GRUB_CMDLINE_LINUX_DEFAULT line:
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
and then make the crub config again:
# grub-mkconfig -o /boo/grub/grub.cfg
**** ryzen 5 crash
add "processor.max_cstate=1" to the kernel boot options
**** apparmor
"apparmor=1 lsm=lockdown,yama,apparmor,bpf""
